---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgBo0Dms3bZ0qLlVaCIRbXvuDNUx1dt7Du+W2VsSbEbCBTC7YId2TOkcfokPegjP0SbDyl5htJk9RErLVluPBM5/DZkhl5bY/X1eOFL4PI5L8pEs9YzPiWnEIrlp5gaT4nF6IoL5dFzMwHR2bHnx4Xy4JBV2PerGVwg8TocIo3Hw2HXZ65kM1dBQoxxLPpk5iLUYr4DG+jZDgw48JBz1UlwTU4KTfnoxOOn6kAdCeK2hojReMd81JD9Gy4h6Tjdk06g/drZzZaIsOd6v2MnzhzSIXVvtbmfC4R0/8oiBJTGBFeZ/DWilB4nRksiMBPhcT7pId/wpkNgYHR0xta+0/UaOWJ7VpLnJ2vwf/uhRY2Zmo0xYgjo/wWn2hjbBslWdhEb0Mfy+IHQ5lwQknrVruykrlo1oWj1oPVr4TVezH0DHAGnN6N1QyKHzD0ivW6b2FAccdRquNpk8ISIqrEN9Lr6x8C9/dh09X21nUyZIujwYMyqjq6nuCGzaLPQBvRAHfr0OK1+k9HRnqPkFsjDSRk0TWHd/k8wMKDevXi42Q9BsQIo0epGVaMbnM0MQdes5TjQ4b28djOUsZn3wXUHCdq80oRAhPZjrr/ScnZEFo6QuAAaL5yZqQhiaUjSFmqwgRD3f/c2nIPK4dfSlTy+tvI82/N8A6mIKNxpfVmL0MmjCbM78roDWptjT2j2YjyAicSOieDyMjCtM0pPbmgqGUEaxbpY3I7hq9RmiYqYaVFfhpId9VTVUlno=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
