apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd
  namespace: argocd
spec:
  project: default
  source:
    chart: httpd
    repoURL: https://api.github.com/repos/luca15mx/argocd-learning/contents/packages/helm/stable/
    targetRevision: 0.1.0
    helm:
      releaseName: httpd
  destination:
    server: 'https://kubernetes.default.svc'
  namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true